services:
  db:
    image: postgres:16
    container_name: seathold_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seathold_db
    volumes:
      - seathold_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  seathold_pgdata:
